"""
Behavior cloning pretraining for Slither RL policies.

Trains a fresh (Recurrent)PPO policy to imitate expert actions from a
chunked dataset generated by collect_expert_data.py.
"""
import argparse
import glob
import json
import os
import random

import numpy as np
import torch
import torch.nn.functional as F
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv, VecMonitor
from sb3_contrib import RecurrentPPO
from tqdm.auto import tqdm

from slither_gym import SlitherEnv
from train import SlitherFeatureExtractor


def parse_args():
    parser = argparse.ArgumentParser(description="Behavior cloning pretraining")
    parser.add_argument("--dataset", type=str, required=True,
                        help="Path to dataset dir (with chunk_*.npz) or a single .npz file")
    parser.add_argument("--output", type=str, default="checkpoints/policy_bc_init",
                        help="Output checkpoint path prefix (SB3 will create .zip)")
    parser.add_argument("--epochs", type=int, default=8)
    parser.add_argument("--batch-size", type=int, default=256)
    parser.add_argument("--lr", type=float, default=1e-4)
    parser.add_argument("--val-ratio", type=float, default=0.1,
                        help="Validation fraction by chunk (0 disables validation)")
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--no-lstm", action="store_true",
                        help="Use feedforward PPO policy instead of RecurrentPPO")
    parser.add_argument("--device", type=str, default="auto",
                        choices=["auto", "cpu", "cuda", "mps"])
    parser.add_argument("--log-every-chunks", type=int, default=10,
                        help="Log training progress every N chunks per epoch")
    return parser.parse_args()


def select_device(device_arg):
    if device_arg != "auto":
        return device_arg
    if torch.backends.mps.is_available():
        return "mps"
    if torch.cuda.is_available():
        return "cuda"
    return "cpu"


def discover_chunks(dataset_path):
    if os.path.isfile(dataset_path):
        if not dataset_path.endswith(".npz"):
            raise ValueError("If --dataset is a file, it must be a .npz")
        return [dataset_path], None

    if not os.path.isdir(dataset_path):
        raise FileNotFoundError(f"Dataset not found: {dataset_path}")

    metadata_path = os.path.join(dataset_path, "metadata.json")
    metadata = None
    if os.path.exists(metadata_path):
        with open(metadata_path, "r", encoding="utf-8") as f:
            metadata = json.load(f)
        chunks = [
            os.path.join(dataset_path, entry["file"])
            for entry in metadata.get("chunks", [])
        ]
    else:
        chunks = sorted(glob.glob(os.path.join(dataset_path, "chunk_*.npz")))

    if not chunks:
        raise RuntimeError(f"No chunk files found in {dataset_path}")
    return chunks, metadata


def split_chunks(chunks, val_ratio, seed):
    if val_ratio <= 0 or len(chunks) < 2:
        return list(chunks), []
    rng = np.random.default_rng(seed)
    indices = np.arange(len(chunks))
    rng.shuffle(indices)
    n_val = max(1, int(round(len(chunks) * val_ratio)))
    n_val = min(n_val, len(chunks) - 1)
    val_set = set(indices[:n_val].tolist())
    train_chunks = [path for idx, path in enumerate(chunks) if idx not in val_set]
    val_chunks = [path for idx, path in enumerate(chunks) if idx in val_set]
    return train_chunks, val_chunks


def create_model(use_lstm, env, device, learning_rate):
    policy_kwargs = {
        "features_extractor_class": SlitherFeatureExtractor,
        "features_extractor_kwargs": {"features_dim": 576},
        "net_arch": dict(pi=[256, 128], vf=[256, 128]),
    }
    if use_lstm:
        policy_kwargs["lstm_hidden_size"] = 256
        policy_kwargs["n_lstm_layers"] = 1
        policy_kwargs["share_features_extractor"] = True

    if use_lstm:
        model = RecurrentPPO(
            "MultiInputLstmPolicy",
            env,
            policy_kwargs=policy_kwargs,
            learning_rate=learning_rate,
            n_steps=2048,
            batch_size=1024,
            n_epochs=10,
            gamma=0.99,
            gae_lambda=0.95,
            clip_range=0.2,
            ent_coef=0.01,
            vf_coef=0.5,
            max_grad_norm=0.5,
            verbose=0,
            tensorboard_log=None,
            device=device,
        )
    else:
        model = PPO(
            "MultiInputPolicy",
            env,
            policy_kwargs=policy_kwargs,
            learning_rate=learning_rate,
            target_kl=0.015,
            n_steps=8192,
            batch_size=1024,
            n_epochs=10,
            gamma=0.99,
            gae_lambda=0.95,
            clip_range=0.2,
            ent_coef=0.01,
            vf_coef=0.5,
            max_grad_norm=0.5,
            verbose=0,
            tensorboard_log=None,
            device=device,
        )
    return model


def preprocess_map(map_array):
    if map_array.dtype == np.uint8:
        return map_array.astype(np.float32) / 255.0
    return map_array.astype(np.float32, copy=False)


def predict_actions(policy, obs_tensor, use_lstm):
    if use_lstm:
        batch_size = obs_tensor["state"].shape[0]
        hidden_size = policy.lstm_actor.hidden_size
        n_layers = policy.lstm_actor.num_layers
        device = obs_tensor["state"].device
        h0 = torch.zeros((n_layers, batch_size, hidden_size), device=device)
        c0 = torch.zeros((n_layers, batch_size, hidden_size), device=device)
        episode_starts = torch.ones((batch_size,), dtype=torch.float32, device=device)
        dist, _ = policy.get_distribution(obs_tensor, (h0, c0), episode_starts)
    else:
        dist = policy.get_distribution(obs_tensor)
    return dist.get_actions(deterministic=True)


def run_epoch(policy, optimizer, chunks, batch_size, device, use_lstm, train_mode, log_every_chunks):
    if train_mode:
        policy.train()
    else:
        policy.eval()

    action_low = torch.as_tensor(policy.action_space.low, dtype=torch.float32, device=device)
    action_high = torch.as_tensor(policy.action_space.high, dtype=torch.float32, device=device)

    sum_loss = 0.0
    sum_steer_mae = 0.0
    sum_boost_acc = 0.0
    sample_count = 0

    mode = "train" if train_mode else "val"
    chunk_iter = tqdm(
        chunks,
        desc=f"{mode} chunks",
        unit="chunk",
        leave=False,
        dynamic_ncols=True,
    )

    for chunk_i, chunk_path in enumerate(chunk_iter, start=1):
        data = np.load(chunk_path, allow_pickle=False)
        maps = preprocess_map(data["map"])
        states = data["state"].astype(np.float32, copy=False)
        targets = data["action"].astype(np.float32, copy=False)
        n = targets.shape[0]

        order = np.arange(n)
        if train_mode:
            np.random.shuffle(order)

        for start in range(0, n, batch_size):
            idx = order[start:start + batch_size]
            obs_tensor = {
                "map": torch.as_tensor(maps[idx], dtype=torch.float32, device=device),
                "state": torch.as_tensor(states[idx], dtype=torch.float32, device=device),
            }
            target_actions = torch.as_tensor(targets[idx], dtype=torch.float32, device=device)

            with torch.set_grad_enabled(train_mode):
                pred_actions = predict_actions(policy, obs_tensor, use_lstm)
                pred_actions = torch.maximum(torch.minimum(pred_actions, action_high), action_low)
                loss = F.mse_loss(pred_actions, target_actions)

                if train_mode:
                    optimizer.zero_grad(set_to_none=True)
                    loss.backward()
                    torch.nn.utils.clip_grad_norm_(policy.parameters(), 0.5)
                    optimizer.step()

            bs = len(idx)
            sum_loss += loss.item() * bs
            sum_steer_mae += torch.mean(torch.abs(
                pred_actions[:, 0] - target_actions[:, 0])).item() * bs
            sum_boost_acc += torch.mean((
                (pred_actions[:, 1] > 0.5) == (target_actions[:, 1] > 0.5)
            ).float()).item() * bs
            sample_count += bs

        if chunk_i % max(1, log_every_chunks) == 0 or chunk_i == len(chunks):
            denom = max(1, sample_count)
            chunk_iter.set_postfix(
                loss=f"{(sum_loss / denom):.4f}",
                steer_mae=f"{(sum_steer_mae / denom):.3f}",
            )

    chunk_iter.close()

    if sample_count == 0:
        return {"loss": 0.0, "steer_mae": 0.0, "boost_acc": 0.0, "samples": 0}

    return {
        "loss": sum_loss / sample_count,
        "steer_mae": sum_steer_mae / sample_count,
        "boost_acc": sum_boost_acc / sample_count,
        "samples": sample_count,
    }


def main():
    args = parse_args()
    random.seed(args.seed)
    np.random.seed(args.seed)
    torch.manual_seed(args.seed)

    if args.epochs <= 0:
        raise ValueError("--epochs must be > 0")
    if args.batch_size <= 0:
        raise ValueError("--batch-size must be > 0")

    chunks, metadata = discover_chunks(args.dataset)
    train_chunks, val_chunks = split_chunks(chunks, args.val_ratio, args.seed)

    device = select_device(args.device)
    use_lstm = not args.no_lstm

    print(f"Dataset chunks: {len(chunks)} (train={len(train_chunks)}, val={len(val_chunks)})")
    if metadata is not None:
        print(f"Expert bot: {metadata.get('bot_type', 'unknown')}")
        print(f"Frames: {metadata.get('total_frames', 'unknown')}")

    dummy_env = VecMonitor(DummyVecEnv([lambda: SlitherEnv(num_scripted=0, num_selfplay=0, max_steps=1)]))
    model = create_model(use_lstm=use_lstm, env=dummy_env, device=device, learning_rate=args.lr)
    policy = model.policy
    optimizer = policy.optimizer

    arch_name = "RecurrentPPO (LSTM)" if use_lstm else "PPO (Feedforward)"
    print(f"Policy: {arch_name}")
    print(f"Device: {device}")
    print(f"Batch size: {args.batch_size}, Epochs: {args.epochs}, LR: {args.lr}\n")

    best_val = float("inf")
    for epoch in range(1, args.epochs + 1):
        print(f"[epoch {epoch}/{args.epochs}] train")
        train_metrics = run_epoch(
            policy=policy,
            optimizer=optimizer,
            chunks=train_chunks,
            batch_size=args.batch_size,
            device=device,
            use_lstm=use_lstm,
            train_mode=True,
            log_every_chunks=args.log_every_chunks,
        )
        print(f"  loss={train_metrics['loss']:.6f} "
              f"steer_mae={train_metrics['steer_mae']:.4f} "
              f"boost_acc={train_metrics['boost_acc'] * 100:.1f}%")

        if val_chunks:
            print(f"[epoch {epoch}/{args.epochs}] val")
            with torch.no_grad():
                val_metrics = run_epoch(
                    policy=policy,
                    optimizer=optimizer,
                    chunks=val_chunks,
                    batch_size=args.batch_size,
                    device=device,
                    use_lstm=use_lstm,
                    train_mode=False,
                    log_every_chunks=args.log_every_chunks,
                )
            print(f"  loss={val_metrics['loss']:.6f} "
                  f"steer_mae={val_metrics['steer_mae']:.4f} "
                  f"boost_acc={val_metrics['boost_acc'] * 100:.1f}%")
            best_val = min(best_val, val_metrics["loss"])

    output_dir = os.path.dirname(args.output)
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)
    model.save(args.output)
    dummy_env.close()

    print(f"\nSaved BC-initialized checkpoint: {args.output}.zip")
    if val_chunks:
        print(f"Best validation loss: {best_val:.6f}")
    print("Use it with: python3 train.py --resume "
          f"{args.output}.zip --stage 2")


if __name__ == "__main__":
    main()
